import pydantic
import typing
import typing_extensions

from .terminal_reader_create_body_metadata_obj0 import (
    TerminalReaderCreateBodyMetadataObj0,
    _SerializerTerminalReaderCreateBodyMetadataObj0,
)


class TerminalReaderCreateBody(typing_extensions.TypedDict, total=False):
    """
    TerminalReaderCreateBody
    """

    expand: typing_extensions.NotRequired[typing.List[str]]
    """
    Specifies which fields in the response should be expanded.
    """

    label: typing_extensions.NotRequired[str]
    """
    Custom label given to the reader for easier identification. If no label is specified, the registration code will be used.
    """

    location: typing_extensions.NotRequired[str]
    """
    The location to assign the reader to.
    """

    metadata: typing_extensions.NotRequired[
        typing.Union[TerminalReaderCreateBodyMetadataObj0, str]
    ]
    """
    Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
    """

    registration_code: typing_extensions.Required[str]
    """
    A code generated by the reader used for registering to an account.
    """


class _SerializerTerminalReaderCreateBody(pydantic.BaseModel):
    """
    Serializer for TerminalReaderCreateBody handling case conversions
    and file omissions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
        extra="allow",
    )
    __pydantic_extra__: typing.Dict[str, typing.Any]

    expand: typing.Optional[typing.List[str]] = pydantic.Field(
        alias="expand", default=None
    )
    label: typing.Optional[str] = pydantic.Field(alias="label", default=None)
    location: typing.Optional[str] = pydantic.Field(alias="location", default=None)
    metadata: typing.Optional[
        typing.Union[_SerializerTerminalReaderCreateBodyMetadataObj0, str]
    ] = pydantic.Field(alias="metadata", default=None)
    registration_code: str = pydantic.Field(
        alias="registration_code",
    )
