import pydantic
import typing
import typing_extensions

from .deleted_tax_id import DeletedTaxId

if typing_extensions.TYPE_CHECKING:
    from .connect_account_reference import ConnectAccountReference
    from .tax_id import TaxId


class InvoiceSettingSubscriptionScheduleSetting(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    account_tax_ids: typing.Optional[
        typing.List[typing.Union[str, "TaxId", DeletedTaxId]]
    ] = pydantic.Field(alias="account_tax_ids", default=None)
    """
    The account tax IDs associated with the subscription schedule. Will be set on invoices generated by the subscription schedule.
    """
    days_until_due: typing.Optional[int] = pydantic.Field(
        alias="days_until_due", default=None
    )
    """
    Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
    """
    issuer: "ConnectAccountReference" = pydantic.Field(
        alias="issuer",
    )
