import pydantic
import typing


class PaymentMethodDetailsPix(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    bank_transaction_id: typing.Optional[str] = pydantic.Field(
        alias="bank_transaction_id", default=None
    )
    """
    Unique transaction id generated by BCB
    """
