import pydantic
import typing
import typing_extensions


if typing_extensions.TYPE_CHECKING:
    from .mandate import Mandate
    from .payment_method import PaymentMethod


class PaymentMethodDetailsIdeal(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    bank: typing.Optional[
        typing_extensions.Literal[
            "abn_amro",
            "asn_bank",
            "bunq",
            "handelsbanken",
            "ing",
            "knab",
            "moneyou",
            "n26",
            "nn",
            "rabobank",
            "regiobank",
            "revolut",
            "sns_bank",
            "triodos_bank",
            "van_lanschot",
            "yoursafe",
        ]
    ] = pydantic.Field(alias="bank", default=None)
    """
    The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `handelsbanken`, `ing`, `knab`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
    """
    bic: typing.Optional[
        typing_extensions.Literal[
            "ABNANL2A",
            "ASNBNL21",
            "BITSNL2A",
            "BUNQNL2A",
            "FVLBNL22",
            "HANDNL2A",
            "INGBNL2A",
            "KNABNL2H",
            "MOYONL21",
            "NNBANL2G",
            "NTSBDEB1",
            "RABONL2U",
            "RBRBNL21",
            "REVOIE23",
            "REVOLT21",
            "SNSBNL2A",
            "TRIONL2U",
        ]
    ] = pydantic.Field(alias="bic", default=None)
    """
    The Bank Identifier Code of the customer's bank.
    """
    generated_sepa_debit: typing.Optional[typing.Union[str, "PaymentMethod"]] = (
        pydantic.Field(alias="generated_sepa_debit", default=None)
    )
    """
    The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    """
    generated_sepa_debit_mandate: typing.Optional[typing.Union[str, "Mandate"]] = (
        pydantic.Field(alias="generated_sepa_debit_mandate", default=None)
    )
    """
    The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
    """
    iban_last4: typing.Optional[str] = pydantic.Field(alias="iban_last4", default=None)
    """
    Last four characters of the IBAN.
    """
    verified_name: typing.Optional[str] = pydantic.Field(
        alias="verified_name", default=None
    )
    """
    Owner's verified full name. Values are verified or provided by iDEAL directly
    (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    """
