import pydantic
import typing
import typing_extensions


if typing_extensions.TYPE_CHECKING:
    from .mandate import Mandate
    from .payment_method import PaymentMethod


class SetupAttemptPaymentMethodDetailsBancontact(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    bank_code: typing.Optional[str] = pydantic.Field(alias="bank_code", default=None)
    """
    Bank code of bank associated with the bank account.
    """
    bank_name: typing.Optional[str] = pydantic.Field(alias="bank_name", default=None)
    """
    Name of the bank associated with the bank account.
    """
    bic: typing.Optional[str] = pydantic.Field(alias="bic", default=None)
    """
    Bank Identifier Code of the bank associated with the bank account.
    """
    generated_sepa_debit: typing.Optional[typing.Union[str, "PaymentMethod"]] = (
        pydantic.Field(alias="generated_sepa_debit", default=None)
    )
    """
    The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    """
    generated_sepa_debit_mandate: typing.Optional[typing.Union[str, "Mandate"]] = (
        pydantic.Field(alias="generated_sepa_debit_mandate", default=None)
    )
    """
    The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
    """
    iban_last4: typing.Optional[str] = pydantic.Field(alias="iban_last4", default=None)
    """
    Last four characters of the IBAN.
    """
    preferred_language: typing.Optional[
        typing_extensions.Literal["de", "en", "fr", "nl"]
    ] = pydantic.Field(alias="preferred_language", default=None)
    """
    Preferred language of the Bancontact authorization page that the customer is redirected to.
    Can be one of `en`, `de`, `fr`, or `nl`
    """
    verified_name: typing.Optional[str] = pydantic.Field(
        alias="verified_name", default=None
    )
    """
    Owner's verified full name. Values are verified or provided by Bancontact directly
    (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    """
