import pydantic
import typing


class SetupIntentPaymentMethodOptionsPaypal1(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    billing_agreement_id: typing.Optional[str] = pydantic.Field(
        alias="billing_agreement_id", default=None
    )
    """
    The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
    """
