import pydantic
import typing
import typing_extensions

from .deleted_tax_id import DeletedTaxId

if typing_extensions.TYPE_CHECKING:
    from .connect_account_reference import ConnectAccountReference
    from .tax_id import TaxId


class SubscriptionsResourceSubscriptionInvoiceSettings(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    account_tax_ids: typing.Optional[
        typing.List[typing.Union[str, "TaxId", DeletedTaxId]]
    ] = pydantic.Field(alias="account_tax_ids", default=None)
    """
    The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
    """
    issuer: "ConnectAccountReference" = pydantic.Field(
        alias="issuer",
    )
